import { chromium, webkit } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

await mkdir('artifacts', { recursive: true });
const useWebKit = process.env.TEST_BROWSER === 'webkit';
const browser = await (useWebKit ? webkit.launch({ headless: true }) : chromium.launch({ channel: 'msedge', headless: true }));
const errors = [];
const baseURL = process.env.TEST_URL || 'http://127.0.0.1:5173';
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, locale: 'ja-JP', timezoneId: 'Asia/Tokyo', ...(useWebKit ? { isMobile: true, hasTouch: true } : {}) });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install({ time: new Date('2026-10-01T06:30:00Z') });
  await page.goto(baseURL);
  await page.locator('h1').waitFor();
  assert.match(await page.locator('h1').innerText(), /こはる/);
  await page.screenshot({ path: `artifacts/desktop${useWebKit ? '-webkit' : ''}.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `artifacts/iphone${useWebKit ? '-webkit' : ''}.png`, fullPage: true });
  for (const width of [320, 375, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No horizontal overflow at ${width}px`);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '自分の記録をはじめる' }).click();
  assert.match(await page.locator('#milk-total').innerText(), /^0/);
  await page.getByRole('button', { name: '授乳・ミルク', exact: true }).click();
  await page.getByRole('button', { name: '140', exact: true }).click();
  await page.getByRole('button', { name: '10ml増やす' }).click();
  await page.locator('#record-note').fill('おいしく飲めた <script>invalid</script>');
  await page.screenshot({ path: `artifacts/record-iphone${useWebKit ? '-webkit' : ''}.png`, fullPage: true });
  await page.getByRole('button', { name: '記録を保存', exact: true }).click();
  assert.match(await page.locator('#milk-total').innerText(), /^150/);
  await page.reload();
  assert.match(await page.locator('#milk-total').innerText(), /^150/);
  assert.equal(await page.locator('.record-info small').innerText(), 'おいしく飲めた <script>invalid</script>');
  await page.locator('.record-row').first().click();
  await page.locator('#record-ml').fill('125');
  await page.getByRole('button', { name: '変更を保存' }).click();
  assert.match(await page.locator('#milk-total').innerText(), /^125/);
  await page.locator('[data-record="pee"]').click();
  await page.locator('#both-check').check();
  await page.getByRole('button', { name: '記録を保存', exact: true }).click();
  assert.equal(await page.locator('.stat-value').nth(2).innerText(), '1回');
  assert.equal(await page.locator('.stat-value').nth(3).innerText(), '1回');
  await page.locator('[data-record="milk"]').click();
  await page.getByRole('button', { name: '母乳（直母）', exact: true }).click();
  await page.locator('#left-minutes').fill('8');
  await page.locator('#right-minutes').fill('7');
  await page.getByRole('button', { name: '記録を保存', exact: true }).click();
  assert.match(await page.locator('#milk-total').innerText(), /^125/);
  assert.equal(await page.locator('.stat-value').nth(1).innerText(), '2回');
  assert.match(await page.locator('.stat-card').nth(1).innerText(), /直母 15 分/);
  await page.locator('.record-row').filter({ hasText: '母乳（直母）' }).click();
  await page.getByRole('button', { name: '削除', exact: true }).click();
  assert.equal(await page.locator('.stat-value').nth(1).innerText(), '1回');
  await page.getByRole('button', { name: '元に戻す' }).click();
  assert.equal(await page.locator('.stat-value').nth(1).innerText(), '2回');
  await page.locator('.mobile-nav [data-action="settings"]').click();
  await page.locator('#baby-name').fill('ひなた');
  await page.locator('#goal-low').fill('600');
  await page.locator('#goal-high').fill('500');
  await page.getByRole('button', { name: '設定を保存' }).click();
  assert.match(await page.locator('#settings-error').innerText(), /上限/);
  await page.locator('#goal-high').fill('800');
  await page.getByRole('button', { name: '設定を保存' }).click();
  assert.match(await page.locator('h1').innerText(), /ひなた/);
  await page.locator('.mobile-nav [data-view="trends"]').click();
  assert.equal(await page.locator('tbody tr').count(), 7);
  await page.locator('.mobile-nav [data-view="guide"]').click();
  assert.equal(await page.locator('.guide-card').count(), 4);
  await page.locator('.mobile-nav [data-view="today"]').click();
  await page.getByRole('button', { name: 'デモを見る' }).click();
  assert.match(await page.locator('h1').innerText(), /こはる/);
  await page.getByRole('button', { name: '自分の記録をはじめる' }).click();
  assert.match(await page.locator('#milk-total').innerText(), /^125/);
  await page.locator('[data-action="prev-day"]').click();
  assert.match(await page.locator('#milk-total').innerText(), /^0/);
  await page.locator('[data-record="milk"]').click();
  assert.match(await page.locator('#record-at').inputValue(), /^2026-09-30/);
  await page.getByRole('button', { name: '記録を保存', exact: true }).click();
  assert.match(await page.locator('#milk-total').innerText(), /^120/);
  await page.locator('[data-action="next-day"]').click();
  assert.match(await page.locator('#milk-total').innerText(), /^125/);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('.mobile-nav [data-action="settings"]').click();
  await page.getByRole('button', { name: '記録を書き出す（JSON）' }).click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /komorebi-real/);
  await page.getByRole('button', { name: '閉じる', exact: true }).click();
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError'); }; });
  await page.locator('[data-record="pee"]').click();
  await page.getByRole('button', { name: '記録を保存', exact: true }).click();
  assert.match(await page.locator('.storage-error').innerText(), /保存できません/);
  assert.deepEqual(errors, []);
  const blocked = await context.request.get(`${baseURL}/.git/config`);
  assert.equal(blocked.status(), 404);
  console.log('Browser checks passed: responsive layouts, create/edit/delete/undo, diapers, breastfeeding, persistence, profiles, goals, date navigation, export, storage failure, and private-file blocking.');
} finally {
  await browser.close();
}
